<!-- barra izquierda-->
<div class="barraIzquierda sticky-top p-2">
    <ul class="nav flex-column">
        <li class="nav-item nav-link">
            <a ng-click="loadNews()" href="index.php?pagina=inicio" class="text-decoration-none text-white letraIzquierda"><i class="fas fa-home mr-2 text-light"></i>Inicio</a>
        </li>
        <li class="nav-item nav-link">
            <a href="index.php?pagina=noticias" class="text-decoration-none text-white letraIzquierda"><i class="fab fa-battle-net mr-2 text-light"></i>Noticias</a>
        </li>
        <li class="nav-item nav-link">
            <a href="index.php?pagina=contacto" class="text-decoration-none text-white letraIzquierda"><i class="fas fa-mobile-alt ml-1 mr-2 text-light"></i>Contacto</a>
        </li class="nav-item nav-link">
        <?php if ($userSession->checkUserPrivileges()) : ?>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown">
                    <i class="fas fa-toolbox ml-1 mr-2 text-light"></i>
                    <span class="text-white">Administrar</span>
                </a>
                <div class="dropdown-menu">
                    <a href="index.php?pagina=administrador&seccion=inicio" class="text-decoration-none text-dark dropdown-item">Panel principal</a>
                    <div class="dropdown-divider"></div>
                    <a href="index.php?pagina=administrador&seccion=crudNoticias" class="text-decoration-none text-dark dropdown-item">Noticias</a>
                    <div class="dropdown-divider"></div>
                    <a href="index.php?pagina=administrador&seccion=crudCategorias" class="text-decoration-none text-dark dropdown-item">Categorias</a>
                    <div class="dropdown-divider"></div>
                    <a href="index.php?pagina=administrador&seccion=crudContactos" class="text-decoration-none text-dark dropdown-item">Contactos</a>
                </div>
            </li>
        <?php endif ?>
        <div>
            <li class="nav-item nav-link text-center">
                <i class="fas fa-search-plus text-muted" id="mas"></i>
                <i class="fas fa-search-minus text-muted" id="menos"></i>
                <i class="fas fa-adjust text-muted" id='tiempo'></i>
            </li>
        </div>
    </ul>
</div>