<nav class="navbar navbar-expand-lg navbar-dark position-fixed barraSuperior">
    <a class="navbar-brand"><img src="img/logo.png" alt="logo" width="auto" height="60px"></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto mr-5">
            <?php if(!$userSession->checkSession()):?>
                    <li class="nav-item nav-link"><a class="btn text-decoration-none text-light letraSuperior" href="index.php?pagina=login">Iniciar sesion</a></li>
                    <li class="nav-item nav-link"><a class="btn text-decoration-none text-light border-light letraSuperior" href="index.php?pagina=register">Registrarse</a></li>
             <?php endif?>
        </ul>

        <!-- perfil -->
        <?php if($userSession->checkSession()):?>
            <div class="form-inline my-2 my-lg-0">
                <a class="text-decoration-none text-dark" href="index.php?pagina=miPerfil">
                    <img class="rounded-circle mr-1" src="../backend/assets<?php echo $_SESSION['user_image']; ?>" alt="imagen perfil usuario" width="36px"height="36px">
                    <span class="mr-3 letraNegra"><?php echo $_SESSION['user_fullname']?></span>
                </a>
                <span>|</span>
                <li class="nav-item nav-link mt-1"><a href="../backend/controllers/logout.php" class="text-decoration-none text-white "><i class="fas fa-sign-out-alt fa-lg"></i></a></li>
            </div>
        <?php endif?>

    </div>
</nav>