<nav class="navbar navbar-expand-md mb-5 position-fixed barraSuperior">
    <div class="container">
       <a href="index.php" class="navbar-brand">Panel de control</a>
        <button type="button" class="navbar-toggler custom-toggler " data-toggle="collapse" data-target="#navbar">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item nav-link"><a href="index.php?pagina=administrador&seccion=inicio" class="text-decoration-none text-white">Panel principal</a></li>
                <li class="nav-item nav-link"><a href="index.php?pagina=administrador&seccion=crudNoticias" class="text-decoration-none text-white">CRUD Noticias</a></li>
                <li class="nav-item nav-link"><a href="index.php?pagina=administrador&seccion=crudCategorias" class="text-decoration-none text-white">CRUD Categorias</a></li>
                <li class="nav-item nav-link"><a href="index.php?pagina=administrador&seccion=crudContactos" class="text-decoration-none text-white">CRUD Contactos</a></li>
                <li class="nav-item nav-link"><a href="../backend/controllers/logout.php" class="text-decoration-none text-white">Cerrar sesión</a></li>
            </ul>
        </div>
   </div>
</nav>