<section>
    <header ng-hide="targetNew == 1" class="seccionNoticia text-white text-center">{{section}}</header>
    <!-- Noticias -->
    <article class="noticia p-5 mb-5" ng-repeat="new in news">
        <a href="index.php?pagina=inicio" ng-click="loadNews()" ng-hide="targetingNew == false"><i class="fas fa-long-arrow-alt-left fa-lg text-dark"></i></a>

        <h1 class="text-center" ng-click="targetNew(new.new_id)" style="cursor: pointer;">{{new.new_title}}</h1>
        <hr class="px-5">

        <form class="calificacion" action="../backend/controllers/addRating.php">
            <input type="radio" name="estrellas" value="5">
            <label for="radio1">★</label>
            <input type="radio" name="estrellas" value="4">
            <label for="radio2">★</label>
            <input type="radio" name="estrellas" value="3">
            <label for="radio3">★</label>
            <input type="radio" name="estrellas" value="2">
            <label for="radio4">★</label>
            <input type="radio" name="estrellas" value="1">
            <label for="radio5">★</label>
        </form>

        <!-- imagen usuario | categoria noticia | fecha creacion -->
        <span class=""><img class="rounded-circle mb-1" src="../backend/assets/{{new.user_image}}" width="32px"
                height="32px"> | {{new.category_name}} | {{new.new_timestamp}}
        </span>
        
        <!-- Imagen noticia (opcional) -->
        <div class="content text-center mt-4 mb-5">
            <img class="img-fluid" src="../backend/assets/{{new.new_image}}" ng-hide="new.new_image == null" width="850em" height="auto">
        </div>

        <!-- cuerpo noticia -->
        <p class="text-left">{{new.new_body}}</p>

        <!-- Sección de comentarios -->
        <hr class="px-5">
        <div class="content mb-1">
            <!-- expande comentarios -->
            
            <button class="btn expandComments bg-transparent" type="button" onclick="expandComments(this)"><i class="far fa-comment-alt mr-1"></i>Comentar</button>

            <div class="content d-inline commentsBox">

                <!-- comentarios -->
                <div class="container mt-3 d-none" ng-repeat="comment in new.comments">
                    <span class="font-weight-bold">{{comment.user_fullname}}</span>
                    <span>{{comment.comment_timestamp}}</span>
                    <p>{{comment.comment_text}}</p>
                </div>

                <!-- campo para comentar -->
                <div class="container mt-3 d-none">
                    <textarea class="form-control mb-1" id="new_body" rows="4" placeholder="Escribe aqui..."
                        style="resize: none;"></textarea>
                    <input type="button" value="Comentar">
                </div>
            </div>
        </div>
    </article>
</section>