<section>
    <header ng-hide="targetNew == 1" class="bg-dark text-white text-center">{{section}}</header>
    <!-- Noticias -->
    <article class="bg-secondary p-2 mb-2" ng-repeat="new in news" style="transition: 2s">

        <a href="index.php?page=inicio" ng-click="loadNews()" ng-hide="targetingNew == false">volver</a>
        <h2 ng-click="targetNew(new.new_id)" style="cursor: pointer;">{{new.new_title}}</h2>

        <form class="clasificacion" action="../backend/controllers/addRating.php">
            <input type="radio" name="estrellas" value="5">
            <label for="radio1">★</label>
            <input type="radio" name="estrellas" value="4">
            <label for="radio2">★</label>
            <input type="radio" name="estrellas" value="3">
            <label for="radio3">★</label>
            <input type="radio" name="estrellas" value="2">
            <label for="radio4">★</label>
            <input type="radio" name="estrellas" value="1">
            <label for="radio5">★</label>
        </form>

        <!-- imagen usuario | categoria noticia | fecha creacion -->
        <span class="ml-2"><img class="rounded-circle mb-1" src="../backend/assets/{{new.user_image}}" width="32px"
                height="32px"> | {{new.category_name}} | {{new.new_timestamp}}
        </span>

        <!-- cuerpo noticia -->
        <p>{{new.new_body}}</p>

        <!-- Imagen noticia (opcional) -->
        <div class="content text-center mb-1">
            <img src="../backend/assets/{{new.new_image}}" ng-hide="new.new_image == null" width="250px" height="250px">
        </div>

        <!-- Sección de comentarios -->
        <div class="content mb-1">

            <h4 class="d-inline">comentarios ({{new.comments.length}})</h4>
            <!-- expande comentarios -->
            <input class="expandComments" type="button" value="+" onclick="expandComments(this)">

            <div class="content d-inline commentsBox">

                <!-- comentarios -->
                <div class="container mt-3 d-none" ng-repeat="comment in new.comments">
                    <span class="font-weight-bold">{{comment.user_fullname}}</span>
                    <span>{{comment.comment_timestamp}}</span>
                    <p>{{comment.comment_text}}</p>
                </div>

                <!-- campo para comentar -->
                <div class="container mt-3 d-none">
                    <textarea class="form-control mb-1" id="new_body" rows="3" placeholder="Escribe aqui..."
                        style="resize: none;"></textarea>
                    <input type="button" value="Comentar">
                </div>
            </div>
        </div>
    </article>
</section>