<!-- **** PERFIL **** -->
<div class="container col-sm-8">
    <div class="col-sm-12 p-0 d-none d-sm-block">
        <h1 class="text-center h3 pt-2"> nombre:Gabriel Alonso Toro Guzman </h1>

        <p>

        </p>

        <p class="lead text-left">
            <b>DESCRIPCION: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas commodo lacus eget nisi cursus 
                                tristique. Ut accumsan mauris eget feugiat dictum. Nunc ut bibendum elit, in luctus risus. Nam 
                                condimentum lorem at elementum pellentesque. In vitae turpis at dolor tempor rhoncus tempus mattis
                                risus. Sed ut ante ullamcorper, aliquet lectus nec, vestibulum metus. Nullam nec turpis sed erat malesuada
                                laoreet. Proin gravida vestibulum erat, at faucibus turpis scelerisque nec. Ut vel tellus quis eros varius
                                faucibus in eu nibh. Pellentesque convallis fermentum interdum. Nullam euismod, libero quis commodo
                                finibus, urna ipsum porta nunc, sit amet molestie orci dui eu nulla. Donec a lectus at odio interdum aliquet
                                quis sit amet purus. Nulla quis vulputate lacus. Nullam bibendum velit id nunc sagittis, nec fringilla nulla
                                ultricies.
            </b><br>
            <a href="editarPerfil.html">Click aca para editar</a>
        </p>
    </div>
</div>